language: ruby
rvm:
  - 2.2
before_script:
  - npm install -g gulp
before_install:
  - npm install -g npm@latest
install:
  - nvm install node
  - nvm use node
  - nvm alias default node
  - gem install jekyll
  - npm install
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "15f5b6818add"
  - COMMIT_AUTHOR_EMAIL: "it@cfms.org"