language: ruby
rvm:
  - 2.2
before_script:
  - npm install -g gulp
before_install:
  - npm install -g npm@latest
install:
  - nvm install node
  - nvm use node
  - nvm alias default node
  - gem install github-pages -v 120
  - npm install
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "9b2a6011a808"
  - COMMIT_AUTHOR_EMAIL: "it@cfms.org"