root: "http://cfms-website.github.io/"
about_cfms: "The CFMS, or the Canadian Federation of Medical Students, represents over 8,000 medical students from 14 Canadian medical student societies from coast to coast. The organization represents medical students to the public, to the federal government, and to national and international medical organizations."

#Set the default layout for a post to the 'news' format
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"

#Number of pages in each archive page.
paginate: 15
paginate_path: "news/archives/:num/"

rdiscount:
  extensions: [smart]

#Settings for the 'featured links' on the homepage:
#--------------------------------------------------

#Featured Link 1
link_url_1: ""
link_text_1: "The 2015 CFMS Annual Review is now available online!"
link_image_url_1: "images/execs/2014-2015/group-pic.jpg"

#Featured Link 2
link_url_2: ""
link_text_2: "This is just another placeholder link"
link_image_url_2: "images/meeting-images/windsor.jpg"

#Featured Link 3
link_url_3: ""
link_text_3: "CFMS Announces Partnership with MD Financial Management"
link_image_url_3: "images/meeting-images/gallery-thumbnails/vancouver-sgm-2015.jpg"
