root: "http://cfms-website.github.io"

#Set the default layout for a post to the 'news' format
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"

#Number of pages in each archive page.
paginate: 12
paginate_path: "news/archives/:num/"

rdiscount:
  extensions: [smart]
