old_site_root: "http://www.old.cfms.org"
about_cfms_en: "The CFMS is an organization representing over 8,000 medical students from 14 Canadian medical student societies from coast to coast. We represent medical students to the public, to the federal government, and to national and international medical organizations."
about_cfms_fr: "La Fédération des étudiants et des étudiantes en médecine du Canada (FEMC) représente les étudiants et les étudiantes en médecine du Canada auprès du gouvernement fédéral, du grand public et des organisations médicales nationales. Nous représentons plus de 8 000 étudiants en médecine fréquentant 14 facultés de médecine canadiennes situées d’un océan à l’autre."

#Firebase URL
firebase_url: "https://amber-heat-9132.firebaseio.com/"
enable_login: true

#MD Financial Management Leadership Award Years (Determines where in the database the files are stored)
enable_leadership_awards: false
leadership_award_years: "2016-2017" 
md_awards_closed_header: "Applications to the CFMS &ndash; MD Financial Management Leadership Awards are currently closed"
md_awards_closed_caption: "Keep an eye out for when applications will open!"

repository: cfms-website/cfms-website.github.io

keep_files: ['stylesheets/', 'js/', 'files/', 'images/']

#Set the default layout for a post to the 'news' format
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: ""
    values:
      lang: "en"
  - 
    scope:
      path: "fr"
    values:
      lang: "fr"

#Number of pages in each archive page.
paginate: 10
paginate_path: "news/archives/:num/"

rdiscount:
  extensions: [smart]

gems: [jekyll-paginate]