old_site_root: "http://www.old.cfms.org"
about_cfms_en: "The CFMS is an organization representing over 8,000 medical students from 14 Canadian medical student societies from coast to coast. We represent medical students to the public, to the federal government, and to national and international medical organizations."
about_cfms_fr: "La Fédération des étudiants et des étudiantes en médecine du Canada (FEMC) représente les étudiants et les étudiantes en médecine du Canada auprès du gouvernement fédéral, du grand public et des organisations médicales nationales. Nous représentons plus de 8 000 étudiants en médecine fréquentant 14 facultés de médecine canadiennes situées d’un océan à l’autre."

#Firebase URL
firebase_url: "https://amber-heat-9132.firebaseio.com/"
enable_login: true

#MD Financial Management Leadership Award Years (Determines where in the database the files are stored)
enable_leadership_awards: true
leadership_award_years: "2017-2018"
md_awards_closed_header: "Applications to the CFMS &ndash; MD Financial Management Leadership Awards are currently closed"
md_awards_closed_caption: "Applications for 2019 year will open in late Fall 2018"

repository: cfms-website/cfms-website.github.io

keep_files: ['stylesheets/', 'js/', 'files/', 'images/']

collections:
  news:
    output: true
  french-news:
    output: true
  humans-of-medicine:
    output: true
  french-humans-of-medicine:
    output: true
  cfms-in-the-news:
    output: true
      

#Set the default layout and language for collections
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news" 
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "news"
      lang: "en"
      permalink: '/news/:year/:month/:day/:title.html'
  -
    scope:
      path: ""
      type: "french-news"
    values:
      layout: "news"
      lang: "fr"
      permalink: '/fr/news/:year/:month/:day/:title.html'
  -
    scope:
      path: ""
      type: "humans-of-medicine"
    values:
      layout: "humans-of-medicine"
      lang: "en"
      excerpt_seperator: '[](More)'
      permalink: '/humans-of-medicine/:year/:month/:day/:title.html'
  -
    scope:
      path: ""
      type: "french-humans-of-medicine"
    values:
      layout: "humans-of-medicine"
      lang: "fr"   
      excerpt_seperator: '[](More)'
      permalink: '/fr/humans-of-medicine/:year/:month/:day/:title.html'
  -
    scope:
      path: ""
    values:
      lang: "en"
  - 
    scope:
      path: "fr"
    values:
      lang: "fr"
       
pagination:
  enabled: true
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2

#paths for the two blogs. If the html files move, this will need updating!
news-blog-paginate-path: "news/archives/:num/"
humans-of-medicine-paginate-path: "humans-of-medicine/:num/"

rdiscount:
  extensions: [smart]

gems: [jekyll-paginate, jekyll-paginate-v2]

#plugins_dir: [_plugins]